### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by HUGEwindow** [openspatial/openspatial-osx#1]
There missing files in your in your example app:
RingScanTableView.h
RingScanTableView.m

**Comment by egradman** [comment]
bump.  this thing doesn't compile.

**Comment by Khwaab** [comment]
Looking into it. Thanks for the note.

**Comment by Khwaab** [comment]
The app now compiles. Though we have not updated our OSX SDK for some time and it may be deprecated. Please note any issues you may have and watch for an update soon.
